# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b0e7f852e0788293c136c4fd0a2a77b5"
name = "Swipe Checkout Global"
application_url = "https://swipe-checkout.vercel.app/"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/api/shopify/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_preferences]
url = "https://swipe-checkout.vercel.app/"
