# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1307128392b3afe1731f2a617f04e4c9"
extension_directories = [ "extensions" ]
name = "Swipe Checkout"
application_url = "https://swipe-checkout.vercel.app/"
embedded = true
handle = "swipe-checkout-saidlabs"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_preferences]
url = "https://swipe-checkout.vercel.app/"
