# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac1c4dc9235186f2ce5c8e8582a6857e"
extension_directories = [ "extensions" ]
name = "Swipe App"
application_url = "https://swipe-checkout.vercel.app/?shopify_app=2"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/api/shopify/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_draft_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_preferences]
url = "https://swipe-checkout.vercel.app/?shopify_app=2"
